image_path1<-"www/images/house_2.png"
image_path2<-"www/images/house_3.png"
image_path3<-"www/images/office.png"
image_path4<-"www/images/park.png"
image_path5<-"www/images/demolition.png"
image_path6<-"www/images/construction.png"
image_path7<-"www/images/empty.png"
image_path8<-"www/images/house_2_transparent.png"
image_path9<-"www/images/house_3_transparent.png"
image_path10<-"www/images/office_transparent.png"
image_path11<-"www/images/park_transparent.png"
image_path12<-"www/images/delete.png"
image_path13<-"www/images/instruction.png"
image_path14<-"www/images/info_1.png"
image_path15<-"www/images/info_2.png"
image_path16<-"www/images/info_3.png"
#image_path17<-"www/images/login_bg.png"
#print(file.exists(image_path17)) 

image_hdb1<-base64enc::dataURI(file=image_path1,mime="image/png")
image_hdb2<-base64enc::dataURI(file=image_path2,mime="image/png")
image_office<-base64enc::dataURI(file=image_path3,mime="image/png")
image_park<-base64enc::dataURI(file=image_path4,mime="image/png")
image_demolition<-base64enc::dataURI(file=image_path5,mime="image/png")
image_construction<-base64enc::dataURI(file=image_path6,mime="image/png")
image_empty<-base64enc::dataURI(file=image_path7,mime="image/png")
image_planned_hdb1<-base64enc::dataURI(file=image_path8,mime="image/png")
image_planned_hdb2<-base64enc::dataURI(file=image_path9,mime="image/png")
image_planned_office<-base64enc::dataURI(file=image_path10,mime="image/png")
image_planned_park<-base64enc::dataURI(file=image_path11,mime="image/png")
image_rubbish<-base64enc::dataURI(file=image_path12,mime="image/png")
image_instruction<-base64enc::dataURI(file=image_path13,mime="image/png")
image_info1<-base64enc::dataURI(file=image_path14,mime="image/png")
image_info2<-base64enc::dataURI(file=image_path15,mime="image/png")
image_info3<-base64enc::dataURI(file=image_path16,mime="image/png")
#image_bg<-base64enc::dataURI(file=image_path17,mime="image/png")
