image_path1<-"images/house_2.png"
image_path2<-"images/house_3.png"
image_path3<-"images/office.png"
image_path4<-"images/park.png"
image_path5<-"images/demolition.png"
image_path6<-"images/construction.png"
image_path7<-"images/empty.png"
image_path8<-"images/house_2_transparent.png"
image_path9<-"images/house_3_transparent.png"
image_path10<-"images/office_transparent.png"
image_path11<-"images/park_transparent.png"
image_path12<-"images/delete.png"
image_path13<-"images/instruction.png"
image_path14<-"images/info_1.png"
image_path15<-"images/info_2.png"
image_path16<-"images/info_3.png"

image_hdb1<-base64enc::dataURI(file=image_path1,mime="image/png")
image_hdb2<-base64enc::dataURI(file=image_path2,mime="image/png")
image_office<-base64enc::dataURI(file=image_path3,mime="image/png")
image_park<-base64enc::dataURI(file=image_path4,mime="image/png")
image_demolition<-base64enc::dataURI(file=image_path5,mime="image/png")
image_construction<-base64enc::dataURI(file=image_path6,mime="image/png")
image_empty<-base64enc::dataURI(file=image_path7,mime="image/png")
image_planned_hdb1<-base64enc::dataURI(file=image_path8,mime="image/png")
image_planned_hdb2<-base64enc::dataURI(file=image_path9,mime="image/png")
image_planned_office<-base64enc::dataURI(file=image_path10,mime="image/png")
image_planned_park<-base64enc::dataURI(file=image_path11,mime="image/png")
image_rubbish<-base64enc::dataURI(file=image_path12,mime="image/png")
image_instruction<-base64enc::dataURI(file=image_path13,mime="image/png")
image_info1<-base64enc::dataURI(file=image_path14,mime="image/png")
image_info2<-base64enc::dataURI(file=image_path15,mime="image/png")
image_info3<-base64enc::dataURI(file=image_path16,mime="image/png")

